### PR TITLE
Strip binary

### PR DESCRIPTION
**Pull request by ehaupt**
Add the strip option in the release profile.

### CODE REVIEW

**Comment by Canop** [comment]
But there's already the strip option...

**Comment by ehaupt** [comment]
> But there's already the strip option...

Sorry, my bad. I've created a [FreeBSD port](https://repology.org/project/backdown/packages) using the latest tagged version [v1.1.0](https://github.com/Canop/backdown/releases/tag/v1.1.0) where the strip option wasn't set. As per requirement for the FreeBSD port I patched `Cargo.toml` [locally](https://cgit.freebsd.org/ports/tree/sysutils/backdown). I'll be able to remove that for the next release.

Please feel free to close the PR.

**Comment by Canop** [comment]
OK, I understand.

I'll make a new tagged release, this will be cleaner, and not just for FreeBSD.

**Comment by Canop** [comment]
@ehaupt I released backdown v1.1.1

**Comment by ehaupt** [comment]
Thank you, I've just updated the [FreeBSD port](https://cgit.freebsd.org/ports/tree/sysutils/backdown) with [this](https://cgit.freebsd.org/ports/commit/?id=49a6f185180c421abff6caeab6fe5397fbfab3cc) commit.

FreeBSD users can install the package with:

```
pkg install backdown
```

or build via ports:

```
cd /usr/ports/sysutils/backdown
make install clean
```

Repology has some nice [badges](https://repology.org/project/backdown/badges) that you might be interested to use. They provide a good overview over the packaging status.

**Pull request closed without merging**
